const AppConstants: any = {
    wareHouse: "Warehouse",
    storage: "Storage",
    inward: "Inward",
    orderProcessing: "Order Processing",
    rto: "RTO",
    return: "Return",
    loading: "Loading",
    unloading: "Unloading",
    stickering: "Stickering",
    allskus:"All SKUs",
    partialskus: "Partial SKUs",
    pricepersticker:"Price Per Sticker",
    inwardStickering: "Inward Stickering",
    pricePerSticker : "Price Per Sticker",
    inwardPricePerSticker : "Inward Price Per Sticker",
    customQC: "Custom QC",
    customqcpricepersticker:"Price Per Piece",
    percentageforqc : "% for QC to Perform",
    packaging: "Packaging",
    otherCharges: "Other Charges",
    inventory: "Inventory",
    packagingMaterial: "Packaging Material",
    freeStorage: "Free Storage",
    b2Cd2C: "B2C/D2C",
    kitting: "Kitting",
    b2B: "B2B",
    returnb2B:"B2B",
    rTVsTN: "RTV/STN",
    internalStocktransfer: "Internal Stock Transfer",
    exemption: "Exemption",
    squareFeet: "Square Feet",
    cft: "CFT",
    piece: "Piece",
    notApplicable: "Not Applicable",
    priceSqFt: "Price/Sq. Ft.",
    minimumSqFt: "Minimum Sq. Ft.",
    minimumMonthlyBillAmount: "Minimum Monthly Bill Amount ( ₹ )",
    fixed: "Fixed",
    calculationExample: "Calculation Example",
    exampleBillAmount: "Example Bill Amount",
    structureType: "Structure Type",
    SqfTrack: "Sq ft/Rack",
    actualUsed: "Actual Used",
    sqft: "Sq. Ft.",
    pricePerSqft: "Price Per Sq. Ft.",
    price: "Price ( ₹ )",
    pricePerCFT: "Price Per CFT",
    rack: "Rack ",
    sku: "SKU",
    rackBasedCalculationExample: "Rack Based Calculation Example",
    cftTrack: "CFT/Rack",
    totalCft: "Total CFT",
    pricePerCft: "Price Per CFT",
    skuBasedcCalculationExample: "SKU Based Calculation Example ",
    skuBased: "SKU Based",
    pricePerSku: "Price Per SKU",
    monthlyCalculationDetailForInventory: "Monthly Calculation detail for Inventory",
    calDetails: "Sum of Daily Count for each SKU for the entire Month / No. of Days in that ",
    monthlyCalculationDetailForActualUsed: "Monthly Calculation detail for Actual Used",
    week1: "Week 1",
    week2: "Week 2",
    week3: "Week 3",
    week4: "Week 4",
    week1Info: "Actual Used count for each day from 1st till 7th. Consider the maximum count of any day in week 1.",
    week2Info: "Actual Used count for each day from 8th till 15th. Consider the maximum count of any day in week 2.",
    week3Info: "Actual Used count for each day from 16th till 22nd. Consider the maximum count of any day in week 3.",
    week4Info: "Actual Used count for each day from 23rd till End of the Month. Consider the maximum count of any day in week 4.",
    perPiece: "Per Piece",
    weightSlab: "Weight Slab",
    category: "Category",
    pricePerPiece: "Price Per Piece",
    pricePerBox: "Price Per Box",
    pieceBasedCalculationExample: "Piece Based Calculation Example",
    inventoryQtyPerMonth: "Inventory Qty Per Month",
    inventoryAvgPerMonth: "Inventory Avg Per Month",
    pricePerPieceCal: "Price Per Piece ( ₹ )",
    totalPrice: "Total Price ( ₹ )",
    monthlyCalculationDetailForPiece: "Monthly Calculation detail for Piece",
    calInfo: "(Sum of Daily Count for each SKU for the entire Month / No. of Days in that Month) X Rate",
    skuBasedCalculationExampleMonthly: "SKU Based Calculation Example (Monthly)",
    weightGms: "Weight (gms)",
    avgInventoryMonth: "Avg Inventory/Month",
    slabPrice: "Slab Price",
    monthlyCalculationDetail: "Monthly Calculation detail",
    monthlyCalInfo: "(Sum of Daily Count for each SKU for the entire Month / No. of Days in that Month) X (Slab Price based on the Weight of the SKU)",
    weightSlabGms: "Weight Slab (gms)",
    priceTxt: "Price",
    categoryCalInfo: "(Sum of Daily Count for each SKU for the entire Month / No. of Days in that Month) X (Price based on the Category of the SKU)",
    categories: "Categories ",
    packingmaterial: "Packing Material",
    cftsft: "CFT/SKU",
    actualused: "Actual Used",
    packingmaterialcalculation: "Packing Material CFT Based Calculation Example(Monthly)",
    minimumorderprocessing:"Minimum Order Processing",
    monthycharges:"Monthy Charges",
    asteric:"(*Includes Order Processing,RTO and Inward)",
    unitwise: "Unit Wise",
    slab: "Slab",
    perorder: "Per Order",
    uptoUnits: "Upto Units",
    priceperAddlunit: "Price Per Addl. Unit",
    orders: "Orders",
    totalUnits: "Total Units",
    addlUnits: "Addl Units",
    fourUnits: "Upto 4 (Unit)",
    calculationExampleMonthly: "Calculation Example - Monthly",
    pricePerOrderTxt: "Price Per Order",
    orderBasedCalculationMonthly: "Order Based Calculation Example (Monthly)",
    pricePerOrder: "Price Per Order ( ₹ )",
    totalPriceTxt: "Total Price",
    totalOrdersForMonth: "Total Orders For Month",
    priceDetermined: "Price would be determined based on the Upto Units",
    volumeDiscountPieces: "Volume discount - Pieces",
    upto: "Upto",
    units: "Units",
    orderSlab_: "Order Slab (Total No. of orders Per Month)",
    perAdditionalUnit: "Per Additional Unit",
    perBox: "Per Box",
    both: "Both",
    inwardBoxesForMonth: "Inward Boxes For Month",
    pieceSlab:"Piece Slab",
    mrp:"MRP",
    box:"Box",
    pieceBasedCalculationExampleMonthly:"Piece Based Calculation Example (Monthly)",
    inwardQtyPerMonth:"Inward Qty Per Month",
    orderProcessed:"Orders Processed",
    pieceProcessed:"Pieces Processed",
    totalNoofOrdersMonth :"Total No. of Orders Per Month : ",
    totalNoofOrdersMonth_ :"Total No. of Orders/Month : ",
    totalNoofPiecesMonth:"Total No. of Pieces Per Month : ",
    weight:"Weight",
    mrpPercentage:"MRP %",
    boxBasedCalculationExampleMonthly:"Box Based Calculation Example (Monthly)",
    inwardBoxesPerMonth:"Inward Boxes Per Month",
    skuCFT:"SKU CFT",
    orderedQtyPerMonth:"Ordered Qty Per Month",
    calculatedCFT:"Calculated CFT",
    skuBasedCalculationExample:"SKU Based Calculation Example",
    mrpBasedCalculationExample:"MRP Based Calculation Example",
    skuMrp:"SKU MRP ( ₹)",
    mrpPrice:"MRP % Price",
    inwardUnitsPerMonth:"Inward Units Per Month",
    inventoryMonth: "Inventory/Month",
    applicable:"Applicable",
    days:"Days",
    perOrder:"Per Order",
    orderSlab:"Order Slab",
    vehicleType: "Vehicle Type",
    tonnage: "Tonnage",
    chargeType: "Charge Type",
    selectVehicle: "Select Vehicle",
    loadingCalculationEx: "Loading Calculation Example (Monthly)",
    pricePerTon: "Price Per Ton",
    totalNoOfConsignments: "Total No Of Consignments",
    pricePerConsignment: "Price Per Consignment",
    totalTons: "Total Tons",
    totalNoOfTonsForEntireMonth: "(Total No Of Tons X Price Per Ton for the entire month)",
    totalNoOfBoxes: "Total no of Boxes",
    totalNoOfBoxesForEntireMonth: "(Total No Of Boxes X Price Per Box for the entire month)",
    exampleBillingAmount: "Example Billing Amount",
    loadingNotApplicable: "Loading Not applicable",
    unloadingNotApplicable: "Unloading Not applicable",
    previous: "Previous",
    orderProcessingNotApplicable: "Order Processing Not applicable",
    contractType: "Contract Type",
    b2cd2c: "B2B/D2C",
    b2b: "B2B",
    selectWarehouse: "Select Warehouse",
    selectedWarehouse: "Selected Warehouse",
    warehouses: "Warehouses",
    quotationCreated: "Quotation Created",
    lastUpdated: "Last Updated",
    draft: "Draft",
    preview: "Preview",
    close: "Close",
    next: "Next",
    status: "Status",
    boxBasedCalculationExample: "Box Based Calculation Example (Monthly)",
    totalNumberOfOrdersPerMonth: "Total No. of orders Per Month :",
    emizaProvidedPackingMaterials:"EMIZA Provided Packing Materials",
    bubbleWrap:"Bubble Wrap",
    brownPapers:"Brown Papers",
    packingTapes:"Packing Tapes",
    customizedPackingTapes:"Customized Packing Tapes",
    standardSKUwiseCartonBoxes:"Standard SKU-wise Carton Boxes",
    customizedCartonBoxes:"Customized Carton Boxes",
    selectBox:"Select Box",
    pricePerUnit:"Price Per Unit",
    customCartonBox1:"Custom Carton Box 1",
    box1:"BOX 1",
    perBundle:"Per Bundle",
    perUnit:"Per Unit",
    reStickeringCharge:"Re-stickering charge",
    rePacking:"Re-packing",
    invoiceAndShippingLabelPrintingCharges:"Invoice and Shipping Label Printing Charges",
    reQC:"Re-QC",
    softwareCharges:"Software Charges",
    repairingPerson:"Repairing Person",
    rtoPerson:"RTO Person",
    personAssistingForDelivery:"Person Assisting for delivery",
    productRefurbishment:"Product Refurbishment",
    executiveOvertime:"Executive Overtime",
    labourerOvertime:"Labourer Overtime",
    additionalManpower:"Additional Manpower",
    serialization:"Serialization",
    internet:"Internet",
    lifecycleManagementB2C:"Lifecycle Management (B2C)",
    holidayCharges:"Holiday Charges",
    electricity:"Electricity",
    perSticker:"Per Sticker",
    perMonth:"Per Month",
    perPerson:"Per Person",
    perHour:'Per Hour',
    perDay:"Per Day",
    volumnDiscountOrder:"Volumn Discount -Order(Total No.of Orders)",
    volumnDiscountBox:"Volumn Discount- Box(Total No.of Box)",
    oneUnits: "Upto 1 (Unit)",
    pricePerBox_: "Price Per Box ( ₹ )",
    exemptionOfTotalOrders:"% Exemption Of Total Orders",
    inwardStickeringNotApplicable: "Inward Stickering Not Applicable",
    customQCnotApplicable: "Custom QC is not applicable",
    consignment: "Consignment",
    qcApplNotesView: "Live Video Camera to be captured for Custom / Detailed QC",
    pricePerPieces: "Price Per Pieces",
    uom:"UOM",
    add:"Add",
    somethingWentWrong:"Something Went Wrong",
    warehouse: "Warehouse",
    client: "Client",
    process: "Process",
    action:"Action",
    remove:"Remove",
    type:" Contract Type",
    module:"Module",
    chargableWeightSlab:"Chargable Weight Slab",
    boxSlab:"Box Slab"
}

export default AppConstants
